// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/CreateArticles": {
            "post": {
                "description": "Create articles",
                "tags": [
                    "ARTICLE"
                ],
                "summary": "Create articles by creations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.CreateArticlesRes"
                        }
                    }
                }
            }
        },
        "/CreateTags": {
            "post": {
                "description": "Create tags",
                "tags": [
                    "TAG"
                ],
                "summary": "Create tags by creations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.CreateTagsRes"
                        }
                    }
                }
            }
        },
        "/DeleteArticles": {
            "post": {
                "description": "Delete articles",
                "tags": [
                    "ARTICLE"
                ],
                "summary": "Delete articles by condition",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.DeleteArticlesRes"
                        }
                    }
                }
            }
        },
        "/DeleteTags": {
            "post": {
                "description": "Delete tags",
                "tags": [
                    "TAG"
                ],
                "summary": "Delete tags by condition",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.DeleteTagsRes"
                        }
                    }
                }
            }
        },
        "/GetArticles": {
            "post": {
                "description": "Get articles",
                "tags": [
                    "ARTICLE"
                ],
                "summary": "Get articles by condition",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.GetArticlesRes"
                        }
                    }
                }
            }
        },
        "/GetTags": {
            "post": {
                "description": "Get tags",
                "tags": [
                    "TAG"
                ],
                "summary": "Get tags by condition",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.GetTagsRes"
                        }
                    }
                }
            }
        },
        "/UpdateArticles": {
            "post": {
                "description": "Update articles",
                "tags": [
                    "ARTICLE"
                ],
                "summary": "Update articles by updations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.UpdateArticlesRes"
                        }
                    }
                }
            }
        },
        "/UpdateTags": {
            "post": {
                "description": "Update tags",
                "tags": [
                    "TAG"
                ],
                "summary": "Update tags by updations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.UpdateTagsRes"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apis.CreateArticlesRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "apis.CreateTagsRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "apis.DeleteArticlesRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "apis.DeleteTagsRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "apis.GetArticlesRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apis.ResArticle"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "apis.GetTagsRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tag"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "apis.ResArticle": {
            "type": "object",
            "properties": {
                "completed_time": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "created_time": {
                    "type": "integer"
                },
                "deleted_time": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_deleted": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tag"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "updated_time": {
                    "type": "integer"
                }
            }
        },
        "apis.UpdateArticlesRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "apis.UpdateTagsRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.Tag": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "TODO LIST API",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
